### ISSUE TITLE
Why  the Train.py-Line#140 [contents]'s parameter is mels?

### ISSUE THREAD

**Issue by niu0717** [CODEJIN/SPEECHSPLIT#2]
Thx, I'm reading your code。And, in the demo of some examples, why is the voice fuzzy。

**Comment by CODEJIN** [comment]
Hi,

## [Parameter of content](https://github.com/CODEJIN/SPEECHSPLIT/blob/6d396dff37482fbef1c9e9eaa7fdcdf97ad036ad/Train.py#L140)
I could not understand your question's intention well. It is based on the paper. In training, the inputs of content and rhyme are same as mel-spectrogram like following:
![image](https://user-images.githubusercontent.com/17133841/92984557-eda62c00-f4e5-11ea-98f4-70cd899e4065.png)

The key point of SpeechSplit is that down-up sampling process and random resampling break several information of mel. And this leads that model does not refer the break information like confusion layer.

## Fuzzy voice

There are several reasons.

1. The learning step may be insufficient. This repository is a personal project and there is a limit of the resources I have. The quality may improve if further steps are trained.

2. There was a problem with the vocoder. I used a vocoder that was in progress as a personal project  for demo, but there was a critical bug in the vocoder code at the time. Currently, the bug has been resolved, but it is difficult to re-train SpeechSplit with different hyper parameters due to the accumulated training queue. It is on the to-do list.

3. There may be some bugs in this SpeechSplit code. Even though I have debugged a few times, this code may also contain bugs. If you find that there is any problem while reading the code, why not post it as an issue? It's a great help to me. :)

Thanks,

Heejo
